import React, { useState, useEffect } from "react";
import { motion } from "motion/react";
import {
  TrendingUp,
  Clock,
  ShoppingBag,
  Users,
  Sparkles,
  ShieldCheck,
  Zap,
  Award,
  MessageCircle,
  Brain,
  RefreshCw
} from "lucide-react";
import { CRMLead, Campaign, AgentConfig } from "../types";
import { getAnalytics, AnalyticsData, aiInsights, AiInsights } from "../lib/api";

interface AnalyticsPanelProps {
  leads: CRMLead[];
  campaigns: Campaign[];
  config: AgentConfig;
}

export default function AnalyticsPanel({ leads, campaigns, config }: AnalyticsPanelProps) {
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);
  const [analytics, setAnalytics] = useState<AnalyticsData | null>(null);
  const [insights, setInsights] = useState<AiInsights | null>(null);
  const [insightsLoading, setInsightsLoading] = useState(false);

  // Load real aggregated analytics from the database
  useEffect(() => {
    getAnalytics().then(setAnalytics).catch(() => setAnalytics(null));
  }, [leads]);

  // AI insights (sentiment + actionable highlights) — generated by Gemini
  const loadInsights = () => {
    setInsightsLoading(true);
    aiInsights()
      .then(setInsights)
      .catch(() => setInsights(null))
      .finally(() => setInsightsLoading(false));
  };
  useEffect(() => { loadInsights(); }, []);

  // Dynamic calculations from the actual live CRM state
  const totalLeads = leads.length;
  const newLeads = leads.filter(l => l.status === "Nuevo").length;
  const contactedLeads = leads.filter(l => l.status === "Contactado").length;
  const budgetedLeads = leads.filter(l => l.status === "Presupuestado").length;
  const closedLeads = leads.filter(l => l.status === "Cerrado").length;
  const totalSalesAmount = leads.reduce((acc, l) => acc + (l.totalSpent || 0), 0);
  const conversionRate = totalLeads > 0 ? ((closedLeads / totalLeads) * 100).toFixed(1) : "0.0";

  // Average Lead Score
  const avgLeadScore = totalLeads > 0
    ? Math.round(leads.reduce((acc, l) => acc + l.score, 0) / totalLeads)
    : 0;

  // Funnel conversion rates between each stage
  const funnelRates = {
    toContactado: newLeads + contactedLeads > 0 ? Math.round((contactedLeads / (newLeads + contactedLeads)) * 100) : 0,
    toPresupuestado: contactedLeads + budgetedLeads > 0 ? Math.round((budgetedLeads / (contactedLeads + budgetedLeads)) * 100) : 0,
    toCerrado: budgetedLeads + closedLeads > 0 ? Math.round((closedLeads / (budgetedLeads + closedLeads)) * 100) : 0,
  };

  // Active campaign count
  const totalCampaigns = campaigns.length;

  // Real monthly sales from DB (last 6 months); empty until real sales close
  const chartData = analytics?.monthlySales?.length
    ? analytics.monthlySales
    : [
        { month: "Ene", sales: 0 }, { month: "Feb", sales: 0 }, { month: "Mar", sales: 0 },
        { month: "Abr", sales: 0 }, { month: "May", sales: 0 }, { month: "Jun", sales: 0 },
      ];

  const totalConversations = analytics?.totalConversations ?? leads.filter(l => l.conversationHistory.length > 0).length;
  const totalInteractions = analytics?.totalMessages ?? 0;
  const channelCounts = analytics?.channelCounts ?? {};
  const channelValues: number[] = Object.values(channelCounts) as number[];
  const totalChannelLeads: number = channelValues.reduce((a, b) => a + b, 0) || 1;

  // 7-day leads sparkline data
  const leadsPerDay = analytics?.leadsPerDay ?? [];
  const maxDayLeads = Math.max(1, ...leadsPerDay.map((d) => d.count));

  // Leads by category breakdown
  const categoryCounts: Record<string, number> = {};
  leads.forEach((l) => {
    const cat = l.category?.trim() || "Sin categoría";
    categoryCounts[cat] = (categoryCounts[cat] || 0) + 1;
  });
  const categoryEntries = Object.entries(categoryCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);
  const maxCategoryCount = Math.max(1, ...categoryEntries.map(([, c]) => c));
  const CATEGORY_COLORS = ["bg-[#3b5bdb]","bg-[#818cf8]","bg-[#7dd87d]","bg-[#ffcf2e]","bg-pink-500","bg-[#3b5bdb]","bg-[#e26562]","bg-[#6366f1]"];

  // Hourly activity heatmap derived from lead lastInteraction timestamps
  const hourCounts = Array.from({ length: 24 }, (_, h) => ({
    hour: h,
    count: leads.filter((l) => new Date(l.lastInteraction).getHours() === h).length,
  }));
  const maxHourCount = Math.max(1, ...hourCounts.map((h) => h.count));

  // Average AI response time (seconds) from conversation history pairs
  const responseTimes: number[] = [];
  leads.forEach((lead) => {
    const hist = lead.conversationHistory;
    for (let i = 0; i < hist.length - 1; i++) {
      if (hist[i].role === "user" && hist[i + 1].role === "model" && hist[i].timestamp && hist[i + 1].timestamp) {
        const delta = (new Date(hist[i + 1].timestamp).getTime() - new Date(hist[i].timestamp).getTime()) / 1000;
        if (delta > 0 && delta < 300) responseTimes.push(delta);
      }
    }
  });
  const avgResponseTimeSec = responseTimes.length
    ? Math.round(responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length)
    : null;

  // Dynamic scaling for the SVG vector line chart to support any dynamic CRM values
  const maxVal = Math.max(...chartData.map(d => d.sales)) || 1;
  const points = chartData.map((data, index) => {
    const xPos = 40 + (index * 108);
    const yPos = 210 - (data.sales / maxVal) * 180;
    return { x: xPos, y: yPos };
  });

  const linePath = `M ${points.map(p => `${p.x} ${p.y}`).join(" L ")}`;
  const areaPath = `M 40 210 L ${points.map(p => `${p.x} ${p.y}`).join(" L ")} L 580 210 Z`;

  // Real KPI Cards mapped from live props state
  const METRICS = [
    {
      title: "Prospectos en Embudo",
      value: `${totalLeads} Leads`,
      sub: "Registrados en vivo",
      desc: `Nuevos: ${newLeads} | Contactados: ${contactedLeads} | Presupuestados: ${budgetedLeads}`,
      color: "from-[#3b5bdb] to-[#3b5bdb]",
      icon: <Users className="text-[#4f6ef7]" size={20} />
    },
    {
      title: "Calificación Promedio",
      value: `${avgLeadScore}%`,
      sub: "Interés de Compra",
      desc: "Puntaje estimado por el modelo de IA basado en los mensajes del cliente.",
      color: "from-[#818cf8] to-[#3b5bdb]",
      icon: <TrendingUp className="text-[#3b5bdb]" size={20} />
    },
    {
      title: "Facturación Concretada",
      value: `$${totalSalesAmount.toLocaleString("es-AR")} ARS`,
      sub: `${closedLeads} cierres de venta`,
      desc: "Ventas finalizadas y cobradas en el panel de control del CRM.",
      color: "from-[#7dd87d] to-[#6366f1]",
      icon: <ShoppingBag className="text-emerald-650" size={20} />
    },
    {
      title: "Tasa de Conversión",
      value: `${conversionRate}%`,
      sub: "Eficiencia de Cierre",
      desc: "Porcentaje de prospectos iniciales que concretaron su compra.",
      color: "from-[#ffcf2e] to-[#ffcf2e]",
      icon: <Clock className="text-[#b8860b]" size={20} />
    }
  ];

  return (
    <div className="space-y-6">

      {/* AI Insights — sentiment + actionable highlights (generated by Gemini) */}
      <div className="bg-white rounded-[22px] p-6 sm:p-7 shadow-card">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-[14px] bg-[#4f6ef7] flex items-center justify-center text-white shrink-0"><Brain size={22} /></div>
            <div>
              <h4 className="font-semibold text-[18px] tracking-tight text-[#111111]">Análisis con IA</h4>
              <p className="text-[13px] text-[#6b7280]">Sentimiento e insights de tu cartera, generados por Gemini</p>
            </div>
          </div>
          <button onClick={loadInsights} disabled={insightsLoading}
            className="px-4 h-9 rounded-full bg-[#f3f5fb] hover:bg-[#eef1fe] text-[#4f6ef7] text-[12.5px] font-medium flex items-center gap-1.5 disabled:opacity-50 cursor-pointer transition-colors">
            <RefreshCw size={13} className={insightsLoading ? "animate-spin" : ""} /> {insightsLoading ? "Analizando…" : "Regenerar"}
          </button>
        </div>

        {insightsLoading && !insights ? (
          <div className="text-[13.5px] text-[#9ca3af] py-8 text-center">Analizando la cartera con IA…</div>
        ) : insights ? (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-7">
            {/* Sentiment */}
            <div>
              <span className="text-[12px] font-semibold text-[#9ca3af] uppercase tracking-wide">Sentimiento de leads</span>
              {(() => {
                const s = insights.sentiment;
                const tot = Math.max(1, s.positive + s.neutral + s.negative);
                const seg = [
                  { label: "Positivo", val: s.positive, color: "bg-[#7dd87d]", text: "text-[#3f9f3f]" },
                  { label: "Neutral", val: s.neutral, color: "bg-[#cbd0e0]", text: "text-[#6b7280]" },
                  { label: "Negativo", val: s.negative, color: "bg-[#f2a5a5]", text: "text-[#c0392b]" },
                ];
                return (
                  <>
                    <div className="flex h-3.5 rounded-full overflow-hidden mt-3 bg-[#f3f5fb]">
                      {seg.map((x) => x.val > 0 ? <div key={x.label} className={x.color} style={{ width: `${(x.val / tot) * 100}%` }} /> : null)}
                    </div>
                    <div className="flex flex-wrap gap-4 mt-3">
                      {seg.map((x) => (
                        <div key={x.label} className="flex items-center gap-1.5">
                          <span className={`w-2.5 h-2.5 rounded-full ${x.color}`} />
                          <span className="text-[13.5px] text-[#4b5563]">{x.label}</span>
                          <span className={`text-[13.5px] font-semibold ${x.text}`}>{x.val}</span>
                        </div>
                      ))}
                    </div>
                  </>
                );
              })()}
              {insights.recommendation && (
                <div className="mt-5 bg-[#eef1fe] rounded-2xl p-4">
                  <span className="text-[12.5px] font-semibold text-[#4f6ef7] flex items-center gap-1.5 mb-1"><Sparkles size={13} /> Recomendación IA</span>
                  <p className="text-[14px] text-[#3b5bdb] leading-relaxed">{insights.recommendation}</p>
                </div>
              )}
            </div>
            {/* Highlights */}
            <div>
              <span className="text-[12px] font-semibold text-[#9ca3af] uppercase tracking-wide">Hallazgos accionables</span>
              <div className="space-y-3 mt-3">
                {insights.highlights.length ? insights.highlights.map((h, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <span className="w-6 h-6 rounded-lg bg-[#eef1fe] text-[#4f6ef7] flex items-center justify-center shrink-0 text-[12px] font-semibold">{i + 1}</span>
                    <p className="text-[14px] text-[#4b5563] leading-relaxed">{h}</p>
                  </div>
                )) : <p className="text-[13.5px] text-[#9ca3af]">Sin hallazgos todavía.</p>}
              </div>
            </div>
          </div>
        ) : (
          <div className="text-[13.5px] text-[#9ca3af] py-8 text-center">No se pudo generar el análisis. Probá "Regenerar".</div>
        )}
      </div>

      {/* Live Agent Status Card — minimalist */}
      <div className="bg-white rounded-[22px] p-6 ds-shadow flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="flex items-center space-x-4">
          <div className="w-12 h-12 rounded-[14px] bg-[#111111] flex items-center justify-center shrink-0 ds-shadow">
            <Zap className="text-white" size={24} />
          </div>
          <div>
            <span className="text-[10px] uppercase font-semibold tracking-wide text-[#4f6ef7] block mb-0.5">
              Agente en vivo
            </span>
            <h4 className="font-semibold text-[17px] tracking-tight text-[#111111]">
              {config.businessName || "Respondo AI"} — operando solo
            </h4>
            <p className="text-[12.5px] text-[#6b7280] max-w-xl leading-relaxed mt-1">
              Entrenado como experto en <strong className="text-[#111111] font-semibold">{config.businessType || "tu rubro"}</strong> con tono <strong className="text-[#111111] font-semibold">{config.tone}</strong>. Responde en milisegundos y deriva al CRM.
            </p>
          </div>
        </div>

        <div className="shrink-0 bg-[#f3f5fb] px-5 py-3 rounded-2xl text-center min-w-[140px]">
          <span className="text-[10px] text-[#9ca3af] block font-semibold uppercase tracking-wide">Tienda</span>
          <span className="text-[17px] font-bold text-[#4f6ef7] block my-0.5 tracking-tight">
            {config.syncStore || "Nativa"}
          </span>
          <span className="text-[9px] text-[#9ca3af] block">Sincronización activa</span>
        </div>
      </div>

      {/* Grid of KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {METRICS.map((m, index) => (
          <div
            key={index}
            className="bg-white rounded-[18px] p-5 hover:ds-shadow transition-all flex flex-col justify-between ds-shadow"
          >
            <div className="flex justify-between items-start mb-3">
              <span className="text-xs font-semibold text-[#9ca3af]">{m.title}</span>
              <div className="p-2 bg-[#f3f5fb] rounded-xl shrink-0">
                {m.icon}
              </div>
            </div>

            <div className="space-y-1">
              <h4 className="font-sans font-black text-2xl text-[#111111] tracking-tight">
                {m.value}
              </h4>
              <span className="text-[10px] font-bold text-[#9ca3af] uppercase tracking-wide block">
                {m.sub}
              </span>
              <p className="text-[10px] text-[#6b7280] leading-normal pt-1 border-t border-[#f4f4f5] mt-2">
                {m.desc}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Pipeline health mini-chart */}
      {totalLeads > 0 && (
        <div className="bg-[#f4f4f5] border border-transparent rounded-2xl p-5 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h4 className="font-sans font-semibold text-sm text-[#27272a]">Salud del Embudo de Ventas</h4>
              <p className="text-xs text-[#6b7280]">Distribución de {totalLeads} leads por etapa del pipeline</p>
            </div>
            <span className="text-xs font-mono font-bold text-[#4f6ef7]">{conversionRate}% conv.</span>
          </div>
          <div className="flex gap-2 items-end h-16">
            {(["Nuevo","Contactado","Presupuestado","Cerrado"] as const).map((status) => {
              const count = leads.filter((l) => l.status === status).length;
              const pct = Math.round((count / totalLeads) * 100);
              const colors: Record<string, string> = {
                Nuevo: "bg-[#818cf8]", Contactado: "bg-[#ffd84d]",
                Presupuestado: "bg-[#818cf8]", Cerrado: "bg-[#7dd87d]",
              };
              return (
                <div key={status} className="flex-1 flex flex-col items-center gap-1">
                  <span className="text-[9px] font-mono text-[#6b7280]">{count}</span>
                  <div className="w-full flex flex-col justify-end" style={{ height: "48px" }}>
                    <div
                      className={`w-full rounded-t-lg transition-all ${colors[status]}`}
                      style={{ height: `${Math.max(4, pct)}%`, minHeight: count > 0 ? "8px" : "0" }}
                    />
                  </div>
                  <span className="text-[8px] text-[#6b7280] text-center leading-tight font-semibold">{status}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Funnel conversion rates */}
      {totalLeads > 0 && (
        <div className="bg-[#f4f4f5] border border-transparent rounded-2xl p-5 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h4 className="font-sans font-semibold text-sm text-[#27272a]">Tasas de Conversión por Etapa</h4>
              <p className="text-xs text-[#6b7280]">% de leads que avanzan entre cada etapa del embudo</p>
            </div>
          </div>
          <div className="flex items-center gap-1">
            {[
              { label: "Nuevo", count: newLeads, color: "bg-[#818cf8] text-sky-700" },
              { label: "→ Contactado", rate: funnelRates.toContactado, color: "text-[#9ca3af]" },
              { label: "Contactado", count: contactedLeads, color: "bg-[#ffd84d] text-[#a67c00]" },
              { label: "→ Presupuestado", rate: funnelRates.toPresupuestado, color: "text-[#9ca3af]" },
              { label: "Presupuestado", count: budgetedLeads, color: "bg-[#818cf8] text-purple-700" },
              { label: "→ Cerrado", rate: funnelRates.toCerrado, color: "text-[#9ca3af]" },
              { label: "Cerrado", count: closedLeads, color: "bg-[#7dd87d] text-[#3f9f3f]" },
            ].map((item, i) =>
              "rate" in item ? (
                <div key={i} className="flex flex-col items-center flex-1 min-w-0">
                  <span className={`text-[10px] font-bold font-mono ${item.rate >= 50 ? "text-[#4caf4c]" : item.rate >= 25 ? "text-[#b8860b]" : "text-[#e26562]"}`}>
                    {item.rate}%
                  </span>
                  <div className="w-full h-0.5 bg-[#e2e5ee] relative">
                    <div className="absolute top-0 right-0 w-0 h-0 border-t-[4px] border-t-transparent border-b-[4px] border-b-transparent border-l-[6px] border-l-[#cbd0e0]" />
                  </div>
                </div>
              ) : (
                <div key={i} className="flex flex-col items-center gap-1 shrink-0">
                  <span className={`text-sm font-black ${item.color.split(" ")[1]}`}>{item.count}</span>
                  <div className={`w-14 h-6 rounded-lg ${item.color.split(" ")[0]} flex items-center justify-center`}>
                    <span className="text-white text-[9px] font-bold">{item.label}</span>
                  </div>
                </div>
              )
            )}
          </div>
        </div>
      )}

      {/* 7-day leads sparkline */}
      {leadsPerDay.length > 0 && (
        <div className="bg-[#f4f4f5] border border-transparent rounded-2xl p-5 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h4 className="font-sans font-semibold text-sm text-[#27272a]">Leads Captados — Últimos 7 Días</h4>
              <p className="text-xs text-[#6b7280]">Nuevos prospectos registrados por día en el CRM</p>
            </div>
            <span className="text-xs font-mono font-bold text-[#4f6ef7]">
              {leadsPerDay.reduce((a, d) => a + d.count, 0)} leads
            </span>
          </div>
          <div className="flex gap-1.5 items-end h-16">
            {leadsPerDay.map((day) => {
              const pct = maxDayLeads > 0 ? Math.round((day.count / maxDayLeads) * 100) : 0;
              return (
                <div key={day.date} className="flex-1 flex flex-col items-center gap-1 group">
                  <span className="text-[9px] font-mono text-[#9ca3af] group-hover:text-[#4f6ef7] transition-colors">
                    {day.count > 0 ? day.count : ""}
                  </span>
                  <div className="w-full flex flex-col justify-end" style={{ height: "44px" }}>
                    <div
                      className="w-full rounded-t-md bg-[#3b5bdb] group-hover:bg-[#4f6ef7] transition-all"
                      style={{ height: `${Math.max(day.count > 0 ? 12 : 3, pct)}%`, opacity: day.count === 0 ? 0.2 : 1 }}
                    />
                  </div>
                  <span className="text-[8px] font-semibold text-[#9ca3af]">{day.label}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Hourly activity heatmap */}
      {leads.length > 0 && (
        <div className="bg-[#f4f4f5] border border-transparent rounded-2xl p-5 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h4 className="font-sans font-semibold text-sm text-[#27272a]">Actividad por Hora del Día</h4>
              <p className="text-xs text-[#6b7280]">Cuándo tus clientes están más activos (basado en última interacción)</p>
            </div>
            <span className="text-xs font-mono font-bold text-[#4f6ef7]">
              {leads.length} interacciones
            </span>
          </div>
          <div className="flex gap-0.5 items-end h-12">
            {hourCounts.map(({ hour, count }) => {
              const intensity = count / maxHourCount;
              const isNight = hour < 7 || hour >= 22;
              return (
                <div key={hour} className="flex-1 flex flex-col items-center gap-0.5 group relative">
                  <div
                    className={`w-full rounded-sm transition-all ${count === 0 ? "bg-[#f4f4f5]" : isNight ? "bg-[#c7d2fe]" : "bg-[#3b5bdb]"}`}
                    style={{ height: `${Math.max(4, intensity * 36)}px`, opacity: count === 0 ? 0.4 : 0.5 + intensity * 0.5 }}
                    title={`${hour}:00 — ${count} lead${count !== 1 ? "s" : ""}`}
                  />
                  {/* Tooltip on hover */}
                  <div className="absolute bottom-full mb-1 left-1/2 -translate-x-1/2 bg-[#111111] text-white text-[8px] font-mono px-1.5 py-0.5 rounded whitespace-nowrap opacity-0 group-hover:opacity-100 pointer-events-none z-10 transition-opacity">
                    {hour}h: {count}
                  </div>
                </div>
              );
            })}
          </div>
          <div className="flex justify-between mt-1 px-0.5">
            <span className="text-[8px] text-[#9ca3af] font-mono">0h</span>
            <span className="text-[8px] text-[#9ca3af] font-mono">6h</span>
            <span className="text-[8px] text-[#9ca3af] font-mono">12h</span>
            <span className="text-[8px] text-[#9ca3af] font-mono">18h</span>
            <span className="text-[8px] text-[#9ca3af] font-mono">23h</span>
          </div>
          {maxHourCount > 0 && (
            <p className="text-[9px] text-[#9ca3af] mt-1.5 text-center">
              Pico: {hourCounts.find(h => h.count === maxHourCount)?.hour}:00 hs
              ({maxHourCount} lead{maxHourCount !== 1 ? "s" : ""})
            </p>
          )}
        </div>
      )}

      {/* Leads by category */}
      {categoryEntries.length > 1 && (
        <div className="bg-[#f4f4f5] border border-transparent rounded-2xl p-5 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h4 className="font-sans font-semibold text-sm text-[#27272a]">Distribución por Categoría / Interés</h4>
              <p className="text-xs text-[#6b7280]">Qué productos o servicios generan más consultas</p>
            </div>
            <span className="text-xs font-mono font-bold text-[#4f6ef7]">{categoryEntries.length} categorías</span>
          </div>
          <div className="space-y-2">
            {categoryEntries.map(([cat, count], i) => {
              const pct = Math.round((count / totalLeads) * 100);
              return (
                <div key={cat} className="space-y-0.5">
                  <div className="flex justify-between text-[10px]">
                    <span className="font-semibold text-[#3f3f46] truncate max-w-[60%]">{cat}</span>
                    <span className="font-mono text-[#6b7280]">{count} lead{count !== 1 ? "s" : ""} · {pct}%</span>
                  </div>
                  <div className="w-full h-2.5 bg-[#f4f4f5] rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all ${CATEGORY_COLORS[i % CATEGORY_COLORS.length]}`}
                      style={{ width: `${Math.max(4, (count / maxCategoryCount) * 100)}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Dynamic SVG Graph Panel */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Chart 1: Interactive Growth Lines */}
        <div className="lg:col-span-8 bg-[#f4f4f5] border border-transparent rounded-3xl p-6 shadow-sm">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h4 className="font-sans font-semibold text-sm text-[#27272a]">Progreso de Ventas Concretadas</h4>
              <p className="text-xs text-[#6b7280]">Volumen mensual acumulado de ventas cobradas directamente en tu CRM</p>
            </div>
            <div className="flex items-center space-x-2 text-xs">
              <span className="flex items-center space-x-1">
                <span className="w-2.5 h-2.5 rounded-full bg-[#3b5bdb] inline-block" />
                <span className="text-[#4b5563] font-medium">Facturación (ARS)</span>
              </span>
            </div>
          </div>

          {/* SVG Vector Line Chart */}
          <div className="relative h-64 w-full">
            <svg viewBox="0 0 600 240" className="w-full h-full overflow-visible">
              {/* Grid Lines */}
              <line x1="40" y1="30" x2="580" y2="30" stroke="#f1f5f9" strokeDasharray="3 3" />
              <line x1="40" y1="80" x2="580" y2="80" stroke="#f1f5f9" strokeDasharray="3 3" />
              <line x1="40" y1="130" x2="580" y2="130" stroke="#f1f5f9" strokeDasharray="3 3" />
              <line x1="40" y1="180" x2="580" y2="180" stroke="#f1f5f9" strokeDasharray="3 3" />
              <line x1="40" y1="210" x2="580" y2="210" stroke="#e2e8f0" strokeWidth="1.5" />

              {/* X Axis Labels */}
              {chartData.map((data, index) => {
                const xPos = 40 + (index * 108);
                return (
                  <text
                    key={index}
                    x={xPos}
                    y="230"
                    fill="#64748b"
                    fontSize="10"
                    textAnchor="middle"
                    className="font-mono font-semibold"
                  >
                    {data.month}
                  </text>
                );
              })}

              {/* Y Axis Labels */}
              <text x="15" y="34" fill="#94a3b8" fontSize="9" textAnchor="start" className="font-mono">{(maxVal / 1000).toFixed(0)}k</text>
              <text x="15" y="84" fill="#94a3b8" fontSize="9" textAnchor="start" className="font-mono">{((maxVal * 0.66) / 1000).toFixed(0)}k</text>
              <text x="15" y="134" fill="#94a3b8" fontSize="9" textAnchor="start" className="font-mono">{((maxVal * 0.33) / 1000).toFixed(0)}k</text>
              <text x="15" y="184" fill="#94a3b8" fontSize="9" textAnchor="start" className="font-mono">0k</text>

              {/* Glistening Area Gradient */}
              <defs>
                <linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#3b82f6" stopOpacity="0.15" />
                  <stop offset="100%" stopColor="#3b82f6" stopOpacity="0" />
                </linearGradient>
              </defs>

              {/* SVG Area */}
              <path
                d={areaPath}
                fill="url(#areaGrad)"
              />

              {/* SVG Line path */}
              <path
                d={linePath}
                fill="none"
                stroke="#3b82f6"
                strokeWidth="3.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />

              {/* Points circles and hover anchors */}
              {chartData.map((data, index) => {
                const xPos = points[index].x;
                const yPos = points[index].y;
                const isHovered = hoveredIndex === index;

                return (
                  <g key={index} className="cursor-pointer">
                    <circle
                      cx={xPos}
                      cy={yPos}
                      r={isHovered ? "7" : "4.5"}
                      fill="#1e40af"
                      stroke="#3b82f6"
                      strokeWidth="2"
                      className="transition-all duration-200"
                    />
                    
                    {/* Hover invisible tracking block */}
                    <rect
                      x={xPos - 30}
                      y="10"
                      width="60"
                      height="200"
                      fill="transparent"
                      onMouseEnter={() => setHoveredIndex(index)}
                      onMouseLeave={() => setHoveredIndex(null)}
                    />

                    {/* Dynamic Tooltip on SVG node */}
                    {isHovered && (
                      <g>
                        <rect
                          x={xPos - 60}
                          y={yPos - 38}
                          width="120"
                          height="28"
                          rx="6"
                          fill="#0f172a"
                          stroke="#1e293b"
                          strokeWidth="1"
                        />
                        <text
                          x={xPos}
                          y={yPos - 20}
                          fill="#fff"
                          fontSize="9"
                          textAnchor="middle"
                          className="font-mono font-bold"
                        >
                          ${data.sales.toLocaleString()} ARS
                        </text>
                      </g>
                    )}
                  </g>
                );
              })}
            </svg>
          </div>
        </div>

        {/* Actividad real del agente */}
        <div className="lg:col-span-4 bg-[#f4f4f5] border border-transparent rounded-3xl p-6 shadow-sm flex flex-col justify-between">
          <div>
            <h4 className="font-sans font-semibold text-sm text-[#27272a]">Actividad del Agente</h4>
            <p className="text-xs text-[#6b7280] mb-6">Métricas reales de conversaciones procesadas por la IA</p>
          </div>

          <div className="space-y-4">
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs">
                <span className="font-bold text-[#3f3f46] flex items-center gap-1"><MessageCircle size={12} className="text-[#4f6ef7]" /> Conversaciones Atendidas</span>
                <span className="text-[#4f6ef7] font-mono font-bold">{totalConversations}</span>
              </div>
              <div className="w-full h-2 bg-[#f4f4f5] border border-[#e2e5ee] rounded-full overflow-hidden">
                <div
                  style={{ width: `${Math.min(100, totalLeads ? (totalConversations / totalLeads) * 100 : 0)}%` }}
                  className="h-full bg-[#3b5bdb] rounded-full"
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <div className="flex justify-between text-xs">
                <span className="font-bold text-[#3f3f46]">Mensajes Procesados</span>
                <span className="text-[#4f6ef7] font-mono font-bold">{totalInteractions}</span>
              </div>
              <div className="w-full h-2 bg-[#f4f4f5] border border-[#e2e5ee] rounded-full overflow-hidden">
                <div
                  style={{ width: totalInteractions > 0 ? `${Math.min(100, (totalInteractions / Math.max(totalInteractions, 200)) * 100)}%` : "0%" }}
                  className="h-full bg-[#3b5bdb] rounded-full transition-all"
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <div className="flex justify-between text-xs">
                <span className="font-bold text-[#3f3f46]">Campañas de Difusión</span>
                <span className="text-[#4caf4c] font-mono font-bold">{totalCampaigns}</span>
              </div>
              <div className="w-full h-2 bg-[#f4f4f5] border border-[#e2e5ee] rounded-full overflow-hidden">
                <div
                  style={{ width: `${Math.min(100, (totalCampaigns / Math.max(totalCampaigns, 5)) * 100)}%` }}
                  className="h-full bg-[#7dd87d] rounded-full transition-all"
                />
              </div>
            </div>

            {/* Avg response time */}
            {avgResponseTimeSec !== null && (
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs">
                  <span className="font-bold text-[#3f3f46] flex items-center gap-1"><Clock size={12} className="text-[#ffcf2e]" /> Tiempo Prom. de Respuesta</span>
                  <span className="text-[#b8860b] font-mono font-bold">
                    {avgResponseTimeSec < 60 ? `${avgResponseTimeSec}s` : `${Math.round(avgResponseTimeSec / 60)}m`}
                  </span>
                </div>
                <div className="w-full h-2 bg-[#f4f4f5] border border-[#e2e5ee] rounded-full overflow-hidden">
                  <div
                    style={{ width: `${Math.min(100, 100 - (avgResponseTimeSec / 30) * 10)}%` }}
                    className="h-full bg-[#ffd84d] rounded-full"
                  />
                </div>
                <p className="text-[8px] text-[#9ca3af]">Tiempo medido entre mensaje del cliente y respuesta del bot</p>
              </div>
            )}

            {/* Channel Breakdown */}
            {Object.keys(channelCounts).length > 0 && (
              <div className="space-y-1.5 pt-1 border-t border-[#f4f4f5]">
                <span className="text-[10px] font-bold text-[#9ca3af] uppercase tracking-wider block">Leads por Canal</span>
                {(["WhatsApp","Instagram","Facebook","Email"] as const).map((ch) => {
                  const count: number = (channelCounts[ch] as number | undefined) ?? 0;
                  const pct: number = Math.round((count / totalChannelLeads) * 100);
                  return count > 0 ? (
                    <div key={ch} className="space-y-0.5">
                      <div className="flex justify-between text-[10px]">
                        <span className="font-semibold text-[#4b5563]">{ch}</span>
                        <span className="font-mono text-[#6b7280]">{count} ({pct}%)</span>
                      </div>
                      <div className="w-full h-1.5 bg-[#f4f4f5] rounded-full overflow-hidden">
                        <div
                          style={{ width: `${pct}%` }}
                          className={`h-full rounded-full transition-all ${ch === "WhatsApp" ? "bg-[#7dd87d]" : ch === "Instagram" ? "bg-pink-500" : ch === "Email" ? "bg-[#6b7280]" : "bg-[#3b5bdb]"}`}
                        />
                      </div>
                    </div>
                  ) : null;
                })}
              </div>
            )}
          </div>

          <div className="mt-6 pt-4 border-t border-[#f4f4f5] text-xs text-[#6b7280] leading-relaxed bg-[#f3f5fb] p-3 rounded-2xl border border-[#e2e5ee]/50">
            <span className="font-semibold text-[#27272a] block mb-1">💡 Datos 100% reales</span>
            Todas las métricas provienen de la base de datos (Supabase). El gráfico de ventas se llena a medida que el agente cierra ventas reales.
          </div>
        </div>

      </div>
    </div>
  );
}
